repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        exclude: ^(yarn.lock|.yarn/)
#      - id: check-json
#      - id: check-yaml
#      - id: detect-aws-credentials
      - id: detect-private-key
#      - id: end-of-file-fixer
#      - id: trailing-whitespace
#      - id: no-commit-to-branch
#        args: [ --branch, main, --branch, master, --pattern, release/.* ]

  - repo: https://github.com/yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: detect secrets
        args: [ '--baseline', '.secrets.baseline' ]
        exclude: ^(yarn.lock|.yarn/)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        entry: prettier --ignore-unknown
#        args: [ '--check' ]
        exclude: ^(skel/|yarn.lock|README.md|.yarn/|.local/|docs/|openapi/)
